name: Linux build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-ubuntu:
    name: build and run on ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build project
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ctest hello-lib-static
        ctest hello-lib-dynamic
    - name: run with static linking
      run: /home/runner/work/hello_world_lib/hello_world_lib/build/bin/hello-bin-static
    - name: run with shared linking
      run: /home/runner/work/hello_world_lib/hello_world_lib/build/bin/hello-bin-dynamic
     
